### ISSUE TITLE
Play a .mp4 File

### ISSUE THREAD

**Issue by lgund** [tapanila/SharpCaster#40]
With Android & Chromecast its possible to play .mp4 files. But if i try to load a mp4 file nothing happens.

`            client.Connected += async delegate { await client.LaunchApplication("B3419EF5"); };
            client.ApplicationStarted += async delegate { await client.LoadMedia("http://www.w3schools.com/html/mov_bbb.mp4"); };
            client.ConnectChromecast(new Uri(selectedChromecast.Tag.ToString()));`

I still just see "SharpCaster demo receiver" :/

I hope you can help me.

Dear
Lukas

**Comment by tapanila** [comment]
The current implementation is excepting the mime type of the stream to be different then MP4. I will add a parameter to LoadMedia where you can specify on next version.

It might take a while so if you want to get started right now then instead of client.LoadMedia...
You can add following

`var startedApplication = client.ChromecastStatus?.Applications?.FirstOrDefault(x => x.AppId == applicationId);
var currentApplicationTransportId = startedApplication.TransportId;
var currentApplicationSessionId = startedApplication.SessionId;

var mediaChannel = client.Channels.First(i => i.Namespace == "urn:x-cast:com.google.cast.media");
var mediaObject = new MediaData("http://www.w3schools.com/html/mov_bbb.mp4", "video/mp4", null, "BUFFERED", 0D, null);
var req = new LoadRequest(currentApplicationSessionId, mediaObject, true, 0.0, null);

var reqJson = req.ToJson();
await mediaChannel.Write(MessageFactory.Load(currentApplicationTransportId, reqJson));`

**Comment by lgund** [comment]
Ok i will try it on the weekend.

When will be the update? If it will this month its good.

Btw is there a way to disconnect to the chromecast or must i wait for the timout?

**Comment by tapanila** [comment]
There will be a new version this month.

There's currently no way to disconnect from the Chromecast. I might also have support for that in next version.

**Comment by lgund** [comment]
then I will wait for your great work ;)... Maybe with your help i can soon send mp4 files from my handy to the chromcast :D.

I will test it tomorrow with that code and will give you a feedback ;)

**Comment by tapanila** [comment]
Did it work for you?

I just released 0.1.7-pre which contains the change to allow you specify the content type while calling LoadMedia. Note that I heavily refactored the stuff and it is not a final version so there will be more major changes before I hit the final 0.1.7

**Comment by lgund** [comment]
Ye i have sawn that new pre release.... I have written you a mail cause I have the problem to get the chromecast connect icon... I have spend today some hours to find a way but it still wont work. After that I can check again the .mp4 file.

Btw great work and thanks for your sdk!

**Comment by tapanila** [comment]
Hmmmm... I have no emails from you.

Just send again to teemu@tapanila.net or add me on skype tapanila.teemu
